name: LinGift
discription: A plugin which can Gift or Send items to other players use things in your inventory
version: 1.1
author: jacklin213

main: me.jacklin213.lingift.LinGift
softdepend: [Vault]

commands:
    lingift:
        description: Send items to other players. Defaults to item in hand.
        usage: /<command> [playername] [amount] (item_id or name) (damage/durability)
        aliases: [gift, send, linsend]